import { Box, HStack } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import RichEditor from '../components/RichEditor';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HStack justifyContent='center' width='100%'>
        <Box borderRadius='10px' background='white' boxShadow='lg' p={6} width='700px' maxWidth='700px'>
          <RichEditor />
        </Box>
      </HStack>
    </>
  );
};

export default Home;
